repository_type: pipeline

nf_core_version: 3.3.2

lint:
  files_unchanged:
    - .prettierignore
    - LICENSE
    - CODE_OF_CONDUCT.md
    - assets/nf-core-biscuit_logo_light.png
    - docs/images/nf-core-biscuit_logo_light.png
    - docs/images/nf-core-biscuit_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .github/CONTRIBUTING.md
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  modules_config: false
  nextflow_config: false
  nf_test_content: false
  multiqc_config: false
  files_exist:
    - .prettierignore
    - .prettierrc.yml
    - conf/base.config
    - conf/modules.config
    - modules.json
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - nf-test.config
    - tests/default.nf.test
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - .github/workflows/branch.yml
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - LICENSE
    - CODE_OF_CONDUCT.md
    - assets/nf-core-biscuit_logo_light.png
    - docs/images/nf-core-biscuit_logo_light.png
    - docs/images/nf-core-biscuit_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - CITATIONS.md
    - conf/igenomes.config
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - nextflow_schema.json
    - docs/output.md
    - docs/README.md
    - docs/usage.md
    - conf/test.config
    - conf/test_full.config
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - assets/multiqc_config.yml
  nfcore_components: false
  schema_lint: false
  schema_params: false
  schema_description: false
  modules_json: false
  base_config: false
  included_configs: false

template:
  org: nf-core
  name: biscuit
  description: Use to run biscuit for wgbs data
  author: lisa.tran251
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - license
    - ci
    - test_config
    - nf-test
    - igenomes
    - modules
    - multiqc
    - fastqc
    - nf_schema
    - nf_core_configs
    - seqera_platform
    - gpu
    - gitpod
    - codespaces
    - vscode
    - code_linters
    - citations
    - documentation
    - rocrate
    - email
    - adaptivecard
    - slackreport
  is_nfcore: false
